services:
  twogether-landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twogether-landing
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3002
